### ISSUE TITLE
SHARED against STATIC compilation of cer_kinematics

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#1]
@barbalberto 

I had to revert back to `STATIC` because in `SHARED` mode tests do not compile against the **`cer_kineamtics`** library and, further, the library doesn't get installed correctly.

I need to develop the code by now, so I need the tests; later on we could investigate this issue.

/cc @drdanz

**Comment by barbalberto** [comment]
Ok, me and Daniele are aware of this problem and we are trying to fix it.
It ia s bit complex because handling this stuff depends a lot on the OS, sorry for the delay.

**Comment by pattacini** [comment]
No problem :+1:

**Comment by pattacini** [comment]
#4 fixes this issue.
