### ISSUE TITLE
Cer double lidar

### ISSUE THREAD

**Issue by valegagge** [robotology/cer#104]
The device gives error during detaching phase.

`[ERROR]Device cer_double_laser_device cannot execute detach 
[ERROR]Cannot run detach action on device cer_double_laser_device 
[INFO]All actions for action level 3 of shutdown phase started. Waiting for unfinished actions. 
[INFO]All actions for action level 3 of shutdown phase finished. 
[INFO]Entering action level 5 of phase shutdown 
[ERROR]Rangefinder2DWrapper: Rangefinder2DWrapper: Sensor returned error
[ERROR]Rangefinder2DWrapper: Rangefinder2DWrapper: Sensor returned error`

**Comment by randaz81** [comment]
This problem has been fixed
