### ISSUE TITLE
Remove https://github.com/robotology/cer/blob/master/gazeboYarpPlugin/README.md

### ISSUE THREAD

**Issue by traversaro** [robotology/cer#112]
It is outdated since commit  https://github.com/robotology/cer/commit/1faabafa315e2c56c004d73fa7448a51c0d223e6 that uses the CMake config files installed by gazebo-yarp-pluging since https://github.com/robotology/gazebo-yarp-plugins/pull/370 . See https://github.com/robotology/cer/issues/84 for more info.

**Comment by traversaro** [comment]
cc @randaz81

**Comment by randaz81** [comment]
Already removed 👍 
Additional compilation issues on CER gazebo-yarp-plugins (i.e. GazeboYarpTripod) have been fixed  by https://github.com/robotology/gazebo-yarp-plugins/pull/485
