### ISSUE TITLE
Wrong sign for R1 torso pitch joint

### ISSUE THREAD

**Issue by randaz81** [robotology/cer#121]
We noticed that on the R1 robot (*) the torso pitch joint encoder value is positive when the torso is bent backward.
**This is not correct, according to several different sources**:

- on the redmine project, on the kinematics page, it is clearly stated the value is positive when the torso is bent forward. I am reporting the relevant picture at the bottom of this issue.
- the urdf file is built according to the redmine specs, so this is ok. And ROS kinematics is built according to this file.
- on the gazebo simulator, the value is positive when the torso is bent forward.

For these reasons, we are going to open a PR on https://github.com/robotology/robots-configuration to fix the sign of the encoder. 

(* verified on SN000 and SN003)

![CERKinematicTree](https://user-images.githubusercontent.com/2869969/121244539-44873900-c89f-11eb-8dd4-d837446d813b.jpg)

**Comment by pattacini** [comment]
Good catch @randaz81 👍🏻 

I'm afraid that the tripod plugin used by the motor control needs to be carefully revised then.

**Comment by pattacini** [comment]
I'll have a look at this the next week, most likely.

**Comment by DatSpace** [comment]
I saw the commit changes the encoder pitch direction for all the robots. Is it verified that the pitch is wrong on the other ones as well ? Just in case.

**Comment by pattacini** [comment]
Hi @DatSpace 

All R1 share the same kinematics of the torso.

**Comment by pattacini** [comment]
In particular, the change impacts all those modules reading/controlling the equivalent joint of the torso.
IK modules instead shouldn't be impacted as they do deal with the physical torso, meaning straight with the 3 elongations.

**Comment by pattacini** [comment]
>I'll have a look at this the next week, most likely.

There's no way I can be on that as said earlier any time soon, unfortunately.
At any rate, for the [reason above](https://github.com/robotology/cer/issues/121#issuecomment-857125695), I feel confident to close the issue and get back quickly to it if needed.
