### ISSUE TITLE
calibration deadlock

### ISSUE THREAD

**Issue by randaz81** [robotology/cer#19]
if a joint does not complete the calibration, it is not possibile to use the joint anymore.

**Comment by ale-git** [comment]
The deadlock is resolved by a timeout. Hardware fault to be added.

**Comment by pattacini** [comment]
@ale-git any update on this?

**Comment by ale-git** [comment]
The deadlock is resolved, at present the tripod returns in a not calibrated state if timeouted, and it can be calibrated again (manually by yarpmotorgui or by yarprobotinterface restart).
