### ISSUE TITLE
[CURRENT_CONTROL] section

### ISSUE THREAD

**Issue by randaz81** [robotology/cer#23]
current pid gains are currently written inside the firmware and are not read from the configuration file

**Comment by ale-git** [comment]
CURRENT_CONTROL section added to the xml files and embobjMotionControl updated with missing "scale" parameter management.

**Comment by randaz81** [comment]
by commit 9772f05ec59c8c97fced488ba3e4ff257ac8f2d8 and https://github.com/robotology/icub-main/commit/78c0e9583bcf630f1ca615f0b602716e20279c38
