### ISSUE TITLE
[VELOCITY_CONTROL] section

### ISSUE THREAD

**Issue by randaz81** [robotology/cer#24]
position control is currently using an internal velocity control loop(?) whose gains are taken from the [POSITION_CONTROL] section and not from [VELOCITY_CONTROL] section.

**Comment by ale-git** [comment]
PID parameters of wormgear velocity control moved to VELOCITY_CONTROL section of the xml files.

**Comment by randaz81** [comment]
by commit 9772f05ec59c8c97fced488ba3e4ff257ac8f2d8
