### ISSUE TITLE
Buy a laptop to replace the cube / Use only one Ubuntu laptop

### ISSUE THREAD

**Issue by lornat75** [robotology/cer#41]
Looks like CER machines with Ubuntu have several stability issues. 

@drdanz @pattacini @randaz81

**Comment by pattacini** [comment]
Ubuntu isn't really a problem by now.
I'd rather change this issue in **We need to replace the cube with a laptop** :smile: 

cc @randaz81 @mbrunettini @lornat75

**Comment by pattacini** [comment]
Actually, we could try to go with only one laptop, preparing the Windows one we have with Ubuntu. I think it could be sufficient.

The **Geomagic** can run on linux; what about the **Oculus** @randaz81?

**Comment by drdanz** [comment]
The Oculus, if they didn't update the linux driver, must run on windows

**Comment by pattacini** [comment]
If I'm not wrong I've heard @randaz81 saying once that the linux driver of the Oculus should be now available.

**Comment by mbrunettini** [comment]
A mobile workstation with windows has been ordered
