### ISSUE TITLE
Message queue not served @ controller rate = 100 Hz

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#46]
We have experienced big problems while controlling reaching with a rate of `100 Hz` (i.e. sample period `Ts = 0.01 s`). What happened was that the internal messages queue got increasing and, as result, the movements got delayed of significant amount of time.

By changing `Ts = 0.1 s`, we improved the situation, even though a rate of `10 Hz` is way low...

cc @randaz81 @barbalberto @ale-git

**Comment by barbalberto** [comment]
This was related to issue #45, and thus solved by 2d5ecd0.

In general case, we see this problem when a `positionMove` or `setPosition` are called on `tripodMotionControl` at "_high_" rate. 
As a rule of thumb, if this error happens again on CER robot, then verify that the code is not calling a loop over single joint for tripod device or position command are not sent at too high frequency.

**Comment by pattacini** [comment]
I deem we can close it for now.
