### ISSUE TITLE
Cameras' custom FW do not allow 640x480 resolution

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#47]
Apparently, the new FW we requested for the cameras to change the brightness values do not allow running in 640x480 mode, but only with higher resolutions. Obviously, this is very problematic in terms of band consumption, and we cannot go back to the previous FW version at the moment.

As temporary workaround, @barbalberto is customizing the device driver with the goal of cropping (to switch from 16:9 to 4:3) and then resizing down the image (to 640x480) at the robot side.

cc @randaz81 @vtikha

**Comment by randaz81** [comment]
@barbalberto can you update (and eventually close if fixed) this issue?

**Comment by barbalberto** [comment]
This has been included in the latest PR related to usbCamera.
User can specify **any desired resolution** when starting the device. OpenCV will crop and rescale the source image to best fit the requirement. This obviously increase the workload on the robot side.
