### ISSUE TITLE
Wrist physical tripod cannot be controlled in velocity

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#50]
As per the title, the physical tripod interface of the wrist doesn't allow any velocity control, whereas the position-direct mode is perfectly working.

We didn't experience any trouble with commanding the physical tripod of the torso in velocity, though.

cc @randaz81

**Comment by ale-git** [comment]
Fixed. The setVelocity command wasn't refreshing the timeout value on Rx. The bug was already fixed, but the fw wasn't updated in the forearms as it was in the torso.
