### ISSUE TITLE
Frequent tripod HW FAULT

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#53]
We do experience frequent HW FAULT of the tripod joints while controlling the mechanism by means of the GUI.

cc @ale-git @randaz81

**Comment by ale-git** [comment]
Exactly in the tripod joints or in the torso yaw? If it is the torso yaw it is due to a misfunction of the fake hall sensors. In the latest version of the 2FOC fw there is a workaround (rare invalid values are ignored), still to be uploaded.

**Comment by pattacini** [comment]
I was mainly referring to the tripod of the wrist.
