### ISSUE TITLE
Ease off the control of the LED screen

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#54]
We need to make the developers' life much easier and:
- [x] Fix the IP of the machine controlling the LED screen once for good.
- [x] Create xml script to launch the services required to display patterns on the LED screen.
- [x] Create System images

cc @barbalberto @mbrunettini 

Please @randaz81 assign the sub-tasks to whom you think might be responsible.

**Comment by mbrunettini** [comment]
I am still waiting a reply for a timeframe (my email of May, the 4th) to accomplish task n.1 and n.3

**Comment by pattacini** [comment]
Thanks @mbrunettini
