### ISSUE TITLE
Fix pronosupination

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#55]
We need to fix and check the sign of the pronosupination joints.
Soon afterwards we do need to verify teleop again.

cc @randaz81 @ale-git

**Comment by ale-git** [comment]
I fixed yersterday the sign of the left pronosupination so that it is like in the model, specular in the two arms: supination should be positive and pronation should be negative. Did you notice something different?

**Comment by pattacini** [comment]
Thanks @ale-git 
Yes, actually, but only during the calibration, 'cause we didn't have the chance to test the left arm yet.
Will do soon.
