### ISSUE TITLE
Head control

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#58]
As of now we cannot control the head, mainly because of mechanical low level problems.
We should thus address this problem at the mechanical stage as much as possible.

This is a note for the design group.

cc @fiorisi @randaz81 @ale-git

**Comment by pattacini** [comment]
#### Update

The encoder has been accommodated on the motor side in order to reduce the impact of backlash.

@ale-git is now coding the modifications to the `FW` required to handle the sensor input.

**Comment by randaz81** [comment]
This improves the controller stability, but does not solve the backlash issue, so the positioning accuracy will be poor.

**Comment by pattacini** [comment]
With the new `FW` it seems we gained quite a nice improvement in the control.

**Comment by pattacini** [comment]
Tested the `gaze controller` on top and it works pretty well and graceful.
I think we can consider this issue solved by now.

Let's not forget to mount a second **AEA at the joint level** to achieve sufficient accuracy during **navigation**.

**Comment by pattacini** [comment]
cc @miggia

**Comment by miggia** [comment]
:kissing_heart:
