### ISSUE TITLE
cer laser (rplidar) does not work

### ISSUE THREAD

**Issue by aerydna** [robotology/cer#62]
The `yarprobotinterface`'s handshake with the current **rpLidar device** (inside `cer-base`) fails. The other rpLidar works fine, so (I presume) the current device must be replaced.

**Comment by pattacini** [comment]
cc @randaz81 @barbalberto

**Comment by barbalberto** [comment]
:+1: yes, we tested together and I can confirm the issue

**Comment by pattacini** [comment]
@aerydna did Emiliano eventually replaced the laser?

**Comment by randaz81** [comment]
CER laser has been replaced with RPLidar2. Since the APIs are different respect to RPLidar1, a new device driver has been added to yarp.
