### ISSUE TITLE
Xtion frames

### ISSUE THREAD

**Issue by pattacini** [robotology/cer#63]
As of now we have one frame attached to the mechanical center of the `Xtion`.

For control purpose, we would need to:
1. Move the frame above called **`depth`** to the actual center of the depth sensor.
2. Introduce a further frame we can call **`depth_rgb`** to be attached to the center of the `Xtion` rgb sensor.

@fiorisi is going to deal with this request (not urgent) next week.
#### Note

Other frames already available are:
- `left`
- `right`
- `cyclopic`, attached to the middle of `left` and `right`
- `gaze`, attached to the middle of the screen

cc @randaz81 @barbalberto @vtikha

**Comment by pattacini** [comment]
#### Note
Other frames already available are:
- `left`
- `right`
- `cyclopic`, attached to the middle of `left` and `right`
- `gaze`, attached to the middle of the screen

**Comment by pattacini** [comment]
@fiorisi please also consider that Marcello is willing to mount asap the new mechanical support of the `Xtion`, which will entail to move the two RGB cameras slightly apart (~ `2 mm`).

Therefore, could you take this into account and provide new DH parameters for the cameras' frames as well?

**Comment by fiorisi** [comment]
Yes, no problem.

**Comment by fiorisi** [comment]
regarding the Xtion, do you want 2 different <sensor> tags (one for the depth sensor and one for the rgb sensor) or do you have a solution to embed the camera inside of the depth (or vice-versa)?

**Comment by pattacini** [comment]
I'd go for **`depth`** and **`depth_rgb`**, as reported above.

**Comment by barbalberto** [comment]
The most flexible solution appears to have 2 different sensors in the urdf/sdf, a rgb and a depth camera.
In this case, playing with config file, we could have the `realistic` robot configuration (rgb and depth camera NOT colocated) or the `ideal` configuration where the 2 sensor are colocated.
(or both)

**Comment by pattacini** [comment]
With @fiorisi we agreed to keep in the model also the fake frame attached to the center of `Xtion` device for control purpose. It will be termed **`depth_center`** (actually it's not cyclopic)

**Comment by fiorisi** [comment]
Testing the following frames: `depth_center`, `depth` and `depth_rgb`.
The test are performed by computing the transform between the `base_link` and the `frame to be tested` using our forward kinematics library and our CAD model.
The position of the joints that belong to the kinematic chain (between  `base_link` and the `frame to be tested`) is defined by the vector **q**. The CAD model is updated accordingly. 

## frame=depth_center

**q=( 0.00000  0.00000  0.00000  0.00000  0.00000  0.00000)**

_IPOPT_
H=-0.00000  0.00000  1.00000  0.02156
-1.00000  0.00000 -0.00000  0.00000
-0.00000 -1.00000  0.00000  1.07240
 0.00000  0.00000  0.00000  1.00000

_CREO_

## ![depth_center](https://cloud.githubusercontent.com/assets/8970230/18762932/6bc4afc4-810b-11e6-9258-cf5c6e9c62f8.JPG)

**q=( 0.01500  0.00000  0.00000  20.00000  15.00000  0.00000)**

_IPOPT_
H= 0.33993 -0.34839  0.87354  0.13368
-0.93969 -0.08852  0.33037  0.00941
-0.03777 -0.93316 -0.35747  1.04557
 0.00000  0.00000  0.00000  1.00000

_CREO_
![depth_center2](https://cloud.githubusercontent.com/assets/8970230/18764614/8d544c56-8112-11e6-9dd6-92afaa0832e0.JPG)

---

## frame=depth

**q=( 0.00000  0.00000  0.00000  0.00000  0.00000  0.00000)**

_IPOPT_
H=-0.00000  0.00000  1.00000  0.02156
-1.00000  0.00000 -0.00000  0.04449
-0.00000 -1.00000  0.00000  1.07240
 0.00000  0.00000  0.00000  1.00000

_CREO_
![depth](https://cloud.githubusercontent.com/assets/8970230/18763107/277134cc-810c-11e6-9b16-4f4becb4b11e.JPG)

---

## frame=depth_rgb

**q=( 0.00000  0.00000  0.00000  0.00000  0.00000  0.00000)**

_IPOPT_
H=-0.00000  0.00000  1.00000  0.02156
-1.00000  0.00000 -0.00000  0.01849
-0.00000 -1.00000  0.00000  1.07240
 0.00000  0.00000  0.00000  1.00000

_CREO_
![depth_rgb](https://cloud.githubusercontent.com/assets/8970230/18763196/8412eb12-810c-11e6-809e-c6f64bb16f28.JPG)

**Comment by fiorisi** [comment]
Testing the following frames: `left`, `right`, `cyclopic` and `gaze`.

## frame=left

**q=( 0.00000  0.00000  0.00000  0.00000  0.00000  0.00000)**

_IPOPT_
H=-0.00000  0.00000  1.00000  0.01385
-1.00000  0.00000 -0.00000  0.03351
-0.00000 -1.00000  0.00000  0.96090
 0.00000  0.00000  0.00000  1.00000

_CREO_
![left](https://cloud.githubusercontent.com/assets/8970230/18776903/93e7a662-816c-11e6-8d27-6870d4542342.JPG)

---

## frame=right

**q=( 0.00000  0.00000  0.00000  0.00000  0.00000  0.00000)**

_IPOPT_
H=-0.00000  0.00000  1.00000  0.01385
-1.00000  0.00000 -0.00000 -0.03351
-0.00000 -1.00000  0.00000  0.96090
 0.00000  0.00000  0.00000  1.00000

_CREO_
![right](https://cloud.githubusercontent.com/assets/8970230/18776934/c6bcd5ee-816c-11e6-94d6-ffe42d8262b4.JPG)

---

## frame=cyclopic

**q=( 0.00000  0.00000  0.00000  0.00000  0.00000  0.00000)**

_IPOPT_
H=-0.00000  0.00000  1.00000  0.01385
-1.00000  0.00000 -0.00000  0.00000
-0.00000 -1.00000  0.00000  0.96090
 0.00000  0.00000  0.00000  1.00000

_CREO_
![cyclopic](https://cloud.githubusercontent.com/assets/8970230/18776952/f94331c0-816c-11e6-97d4-5e3897d6f1f9.JPG)

---

## frame=gaze

**q=( 0.00000  0.00000  0.00000  0.00000  0.00000  0.00000)**

_IPOPT_
H=-0.00000  0.00000  1.00000  0.01116
-1.00000  0.00000 -0.00000  0.00000
-0.00000 -1.00000  0.00000  1.01450
 0.00000  0.00000  0.00000  1.00000

_CREO_
![gaze](https://cloud.githubusercontent.com/assets/8970230/18776998/314e6db4-816d-11e6-8222-4dc82416c9d8.JPG)

**Comment by pattacini** [comment]
Thank you @fiorisi !
