### ISSUE TITLE
joystick controls are not correctly mapped

### ISSUE THREAD

**Issue by randaz81** [robotology/cer#70]
In order to disable the joystick hats, and interpret the values as joystick axis, the following environment variables need to be included in the robot .bashrc file

> export SDL_LINUX_JOYSTICK="'Xbox Gamepad (userspace driver)' 8 0 0"
> export SDL_LINUX_JOYSTICK="/dev/input/js0"

@mbrunettini please take note of these variables for future R1 releases.

PS: I also removed some annoying warning by placing the following line in  /etc/modprobe.d/blacklist.conf 

> blacklist xpad

The xboxdrv driver is launched during system boot by the line:

> xboxdrv --silent

which is placed in /etc/rc.local (it needs launched as root)

**Comment by mbrunettini** [comment]
Thanks @randaz81, modification to cer-base system have been recorded in Redmine Feature 784
