### ISSUE TITLE
tripodMotionControl not congruent to simulation model.

### ISSUE THREAD

**Issue by ale-git** [robotology/cer#74]
The `bool TripodSolver::ikin(const Vector &hpr, Vector &lll, int *exit_code)` and `bool TripodSolver::fkin(const Vector &lll, Vector &hpr)` functions implicitly assume that the equivalent joint order is heave->pitch->roll, but in the simulation model the order is heave->roll->pitch instead. They make use of the `dcm2rpy()` and `rpy2dcm()` functions discarding the yaw part, usually small, but they don't give correct values for roll and pitch because they are calculated assuming that pitch comes before roll as in the usual yaw->picth->roll representation.
https://github.com/robotology/cer/blob/master/cermod/tripod/tripodMotionControl.cpp

**Comment by pattacini** [comment]
We agreed to implement equivalent methods `ypr2dcm()` and `dcm2ypr()` in Yarp in order to then fix the problem.

**Comment by pattacini** [comment]
@barbalberto the new methods will be called from within `fkin` and `ikin` services, therefore, in principle, no changes are required in `tripodMotionControl`.

**Comment by pattacini** [comment]
Upon https://github.com/robotology/yarp/pull/1138 and https://github.com/robotology/cer/commit/840605aeca728a111744a48c26150223282d51d5, this issue should be fixed by now.

**Comment by ale-git** [comment]
Yes, let's close it.

**Comment by barbalberto** [comment]
Great! Thanks
