### ISSUE TITLE
tripodMotionControl.h includes the old yarp/dev/ControlBoardInterfacesImpl.inl

### ISSUE THREAD

**Issue by miccol** [robotology/cer#93]
Since in YARP 3.0 the file `yarp/dev/ControlBoardInterfacesImpl.inl` was renamed
`yarp/dev/ControlBoardInterfacesImpl-inl.h`

The following include should be updated accordingly.
https://github.com/robotology/cer/blob/c3d206618d0d1a231d0ebd16a84e2b01c63a5dbf/cermod/tripod/tripodMotionControl.h#L32

Cheers,

MC

**Comment by Nicogene** [comment]
Feel free to open a PR :stuck_out_tongue:
